name: flutter_category_feature
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  hive: ^2.2.3
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  path_provider: ^2.1.5
  get_it: ^8.0.3
  uuid: ^4.5.1
  reorderable_grid_view: ^2.2.8
  flutter_svg: ^2.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.4.15



flutter:
  uses-material-design: true
  assets:
    - assets/icons/


